// <auto-generated />
using ERP.Host;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ERP.Host.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260604000004_AddAcademicsModule")]
    partial class AddAcademicsModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
    }
}
